### ISSUE TITLE
Update prover's README

### ISSUE THREAD

**Issue by learnerLj** [scroll-tech/scroll#1081] opened 2024-01-18 19:10 UTC
Following the instructions in its readme, I found that the build process did not generate the dynamic link library, and it threw errors like 'error while loading shared libraries: libzktrie.so: cannot open shared object file: No such file or directory' after running 'go test'."
![image](https://github.com/scroll-tech/scroll/assets/72367122/8ac4cf33-898b-4eb7-942f-86fb18b1c918)

**Comment by georgehao** [comment] 2024-01-19 02:10
```
make libzkp
go test -tags="gpu ffi" -timeout 0 -c core/prover_test.go
```
For reference

**Comment by etherbiln** [comment] 2024-02-14 12:48
First, ensure that all specified dependencies are correctly installed. Make sure library files and other necessary dependencies are available. @georgehao

**Comment by Thegaram** [comment] 2024-02-18 16:50
Closing for now, please reopen and provide more details if the issue is not resolved.

**Closed as completed by Thegaram** 2024-02-18 16:50 UTC
